openapi: 3.0.3
info:
  title: Camera Control API
  version: "1.0"
servers:
  - url: /api/v1
paths:
  /cameras:
    get:
      summary: Get list of cameras
      operationId: getCameras
      responses:
        "200":
          description: List of available cameras
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCamerasResponse"

  /camera/{camera_id}/ptz:
    post:
      summary: Start PTZ control
      operationId: startPtz
      parameters:
        - name: camera_id
          in: path
          required: true
          schema:
            type: string
          description: Camera identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartPtzRequest"
      responses:
        "200":
          description: PTZ started
    delete:
      summary: Stop PTZ control
      operationId: stopPtz
      parameters:
        - name: camera_id
          in: path
          required: true
          schema:
            type: string
          description: Camera identifier
      responses:
        "200":
          description: PTZ stopped

  /camera/{camera_id}/webrtc:
    post:
      summary: Setup WebRTC session
      operationId: setupWebRTC
      parameters:
        - name: camera_id
          in: path
          required: true
          schema:
            type: string
          description: Camera identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetupWebRTCRequest"
      responses:
        "200":
          description: WebRTC connection info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SetupWebRTCResponse"

components:
  schemas:
    CameraDescription:
      type: object
      properties:
        label:
          type: string
        description:
          type: string
      required: [label, description]

    GetCamerasResponse:
      type: object
      properties:
        cameras:
          type: array
          items:
            $ref: "#/components/schemas/CameraDescription"
      required: [cameras]

    Velocity:
      type: object
      properties:
        pan:
          type: number
          format: float
        tilt:
          type: number
          format: float
        zoom:
          type: number
          format: float
      required: [pan, tilt, zoom]

    StartPtzRequest:
      type: object
      properties:
        velocity:
          $ref: "#/components/schemas/Velocity"
        deadline:
          type: string
          description: Deadline timestamp (RFC3339 or ISO8601)
      required: [velocity, deadline]

    SetupWebRTCRequest:
      type: object
      properties:
        offer_b64:
          type: string
          description: Base64-encoded SDP offer
      required: [offer_b64]

    SetupWebRTCResponse:
      type: object
      properties:
        id:
          type: string
        local_desc_b64:
          type: string
          description: Base64-encoded local SDP answer
      required: [id, local_desc_b64]
